"""initial_schema

Revision ID: 299f80315aad
Revises: 
Create Date: 2026-04-04 16:27:05.171785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '299f80315aad'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredientref',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('density', sa.Float(), nullable=True),
    sa.Column('default_unit', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['ingredientref.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingredientref_name'), 'ingredientref', ['name'], unique=True)
    op.create_index(op.f('ix_ingredientref_slug'), 'ingredientref', ['slug'], unique=True)
    op.create_table('pendingpackage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('asset_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pendingpackage_tag_name'), 'pendingpackage', ['tag_name'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text("true")),
    sa.Column('is_admin', sa.Boolean(), nullable=False, server_default=sa.text("false")),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('recipe',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('folder_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('difficulty', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('active_time', sa.Integer(), nullable=True),
    sa.Column('total_time', sa.Integer(), nullable=True),
    sa.Column('portions', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('content_md', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ingredients_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('steps_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('nutrition_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False, server_default=sa.text("false")),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('image_main', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipe_folder_name'), 'recipe', ['folder_name'], unique=False)
    op.create_index(op.f('ix_recipe_slug'), 'recipe', ['slug'], unique=False)
    op.create_index(op.f('ix_recipe_title'), 'recipe', ['title'], unique=False)
    op.create_table('mealplan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('planned_date', sa.DateTime(), nullable=False),
    sa.Column('meal_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipeingredient',
    sa.Column('recipe_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ingredient_ref_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('raw_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_ref_id'], ['ingredientref.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], ),
    sa.PrimaryKeyConstraint('recipe_id', 'ingredient_ref_id')
    )
    op.create_table('userfavorite',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'recipe_id')
    )
    op.create_table('userrecipenote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('userrecipenote')
    op.drop_table('userfavorite')
    op.drop_table('recipeingredient')
    op.drop_table('mealplan')
    op.drop_index(op.f('ix_recipe_title'), table_name='recipe')
    op.drop_index(op.f('ix_recipe_slug'), table_name='recipe')
    op.drop_index(op.f('ix_recipe_folder_name'), table_name='recipe')
    op.drop_table('recipe')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_pendingpackage_tag_name'), table_name='pendingpackage')
    op.drop_table('pendingpackage')
    op.drop_index(op.f('ix_ingredientref_slug'), table_name='ingredientref')
    op.drop_index(op.f('ix_ingredientref_name'), table_name='ingredientref')
    op.drop_table('ingredientref')
    # ### end Alembic commands ###
