"""drop pendingpackage table

Revision ID: 9549c007592f
Revises: cd597b9c4df7
Create Date: 2026-04-04 22:05:44.068960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9549c007592f'
down_revision: Union[str, None] = 'cd597b9c4df7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pendingpackage_tag_name'), table_name='pendingpackage')
    op.drop_table('pendingpackage')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pendingpackage',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tag_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('asset_url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('detected_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pendingpackage_pkey'))
    )
    op.create_index(op.f('ix_pendingpackage_tag_name'), 'pendingpackage', ['tag_name'], unique=True)
    # ### end Alembic commands ###
