"""add_shopping_list_exclusion_table

Revision ID: cf346dcc1627
Revises: 02e50dbd4ba7
Create Date: 2026-04-08 12:04:09.666936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cf346dcc1627'
down_revision: Union[str, None] = '02e50dbd4ba7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shoppinglistexclusion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ingredient_raw', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shoppinglistexclusion_ingredient_raw'), 'shoppinglistexclusion', ['ingredient_raw'], unique=False)
    op.create_index(op.f('ix_shoppinglistexclusion_recipe_id'), 'shoppinglistexclusion', ['recipe_id'], unique=False)
    op.create_index(op.f('ix_shoppinglistexclusion_user_id'), 'shoppinglistexclusion', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shoppinglistexclusion_user_id'), table_name='shoppinglistexclusion')
    op.drop_index(op.f('ix_shoppinglistexclusion_recipe_id'), table_name='shoppinglistexclusion')
    op.drop_index(op.f('ix_shoppinglistexclusion_ingredient_raw'), table_name='shoppinglistexclusion')
    op.drop_table('shoppinglistexclusion')
    # ### end Alembic commands ###
