// Mots-clés reconnus à l'intérieur des blocs {réglage Thermomix}
// La clé est en minuscules pour une comparaison insensible à la casse.
export const KEYWORD_ICON_MAP: Record<string, string> = {
  // Modes de base (TM5/TM6)
  'varoma':        '\ue008',
  'pétrin':        '\ue001',
  'inverse':       '\ue003',
  'mijotage':      '\ue002',
  'turbo':         '\ue00b',
  // Modes spéciaux TM6
  'nettoyage':     '\ue011',
  'sous-vide':     '\ue02d',
  'mixage':        '\ue01e',
  'rice cooker':   '\ue00d',
  'fermentation':  '\ue02e',
  'cuisson lente': '\ue018',
  'caramel':       '\ue00c',
  'bouilloire':    '\ue016',
  'éplucher':      '\ue038',
  'épaissir':            '\ue031',
  // Tags symboliques identifiés
  'cuisson des œufs':   '\ue033',
  'râper':              '\ue036',
  'émincer':            '\ue037',
  'découper en spirale':'\ue04c',
  'cuisson sans couvercle': '\ue937',
};

export const ICON_MAP: Record<string, string> = {
  '[KNEAD]': '\ue001',
  '[SYM_E001]': '\ue001',
  '[STIR]': '\ue002',
  '[REVERSE]': '\ue003',
  '[VAROMA]': '\ue008',
  '[TURBO]': '\ue00b',
  '[CARAMEL]': '\ue00c',
  '[RICE]': '\ue00d',
  '[CUP]': '\ue00e',
  '[BASKET]': '\ue00f',
  '[CLEAN]': '\ue011',
  '[CREAM]': '\ue012',
  '[STEW]': '\ue014',
  '[KETTLE]': '\ue016',
  '[SLOW]': '\ue018',
  '[SYM_E019]': '\ue019',
  '[BLEND]': '\ue01e',
  '[SYM_E033]': '\ue033',
  '[SYM_E036]': '\ue036',
  '[SYM_E037]': '\ue037',
  '[SYM_E038]': '\ue038',
  '[SOUSVIDE]': '\ue02d',
  '[FERMENT]': '\ue02e',
  '[AUTO]': '\ue030',
  '[THICKEN]': '\ue031',
  '[EGG]': '\ue03c',
  '[WARMUP]': '\ue03d',
  '[PEEL]': '\ue038',
  '[SYM_E04C]': '\ue04c',
  '[SYM_E904]': '\ue904',
  '[SYM_E937]': '\ue937',
};
